spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: fcfootballapi@gmail.com
    password: ${FC_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${FC_GOOGLE_CLIENT_ID}
            client-secret: ${FC_GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  cors:
    allowedOrigins:

  oauth2:
    authorizedRedirectUris:



  mail:
    expirationTimeInMin: 15
    confrimationLink: http://localhost:8080/api/v1/auth/confirm?token=

  tokenJWT:
    expirationTimeInMs: 43200000
    secret: ${JWT_SECRET}