spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${FC_DB_URL}
    username: ${FC_DB_USERNAME}
    password: ${FC_DB_PASSWORD}


  mail:
    host: smtp.gmail.com
    port: 587
    username: fcfootballapi@gmail.com
    password: ${FC_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${FC_GOOGLE_CLIENT_ID}
            client-secret: ${FC_GOOGLE_CLIENT_SECRET}
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  cors:
    allowedOrigins:  https://fcfootball.azurewebsites.azurewebsites.net

  oauth2:
    authorizedRedirectUris:
      - https://fcfootball.azurewebsites.net/api/v1/test/all
      - https://fcfootball.azurewebsites.net/api/v1/auth/oauth2/token



  mail:
    expirationTimeInMin: 15
    confrimationLink: https://fcfootball.azurewebsites.net/api/v1/auth/confirm?token=

  tokenJWT:
    expirationTimeInMs: 43200000
    secret: ${JWT_SECRET}