create schema if not exists dbo;

create table if not exists users (
                       id bigint generated by default as identity,
                       email varchar(50),
                       first_name varchar(255),
                       is_enabled boolean not null,
                       last_name varchar(255),
                       password varchar(255),
                       provider varchar(255),
                       primary key (id)
);

create table if not exists roles (
                       id integer generated by default as identity,
                       name varchar(20),
                       primary key (id)
);

create table if not exists user_roles (
                                          user_id bigint not null,
                                          role_id integer not null,
                                          primary key (user_id, role_id),
    foreign key (user_id) references users (id) on delete cascade,
    foreign key (role_id) references roles (id) on delete cascade
);
